version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=coffeShop
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: