import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../styles"
import StoreProvider from "../store/StoreProvider"
import Header from "@/widges/header/ui/Header"
import Footer from "@/widges/Footer/ui/Footer"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: {
    default:"Create Next App",
    template:"%s | qwe",
  },
  description: "Generated by create next app",
}

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <StoreProvider>
      <html lang="en">

        <body className={inter.className}>
          <div className="wrapper">
            <Header />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    </StoreProvider>
  )
  
}
