import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '../styles';
import Providers from '../store/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>

        {children}
        </Providers>
        </body>
    </html>
  );
}
