import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "../styles"
import StoreProvider from "../store/StoreProvider"
import Header from "@/widges/header/ui/Header"
import Footer from "@/widges/Footer/ui/Footer"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          <Footer/>
        </body>
      </html>
    </StoreProvider>
  )
}
